{{- if .Values.isAutomaticPermissions }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  {{- with .Values.labels }}
  labels:  
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.app.name }}
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
      - namespaces
    verbs:
      - list
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
{{- end }}