{{- if .Values.isAutomaticPermissions }}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.labels }}
  labels:  
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
    iam.gke.io/gcp-service-account: {{ required "GCP service account must be supplied, binded and given the correct permissions" .Values.gcpServiceAccount }}
  {{- with .Values.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ .Values.app.name }}
{{- end }}